### ISSUE TITLE
Without cookies, buttons border

### ISSUE THREAD

**Issue by axbecher** [hurr13ane/hurr13ane.com#6]
Without cookies, buttons don't have border. 

Without cookies: 
![image](https://user-images.githubusercontent.com/72851811/161105993-9b17803d-98d7-4130-b86b-ea24d3462ef1.png)

With cookies:
![image](https://user-images.githubusercontent.com/72851811/161106030-f0221905-2d46-4aed-9075-a478d89fd2cf.png)

Expected result: 
Website should load one between light or dark theme.

**Comment by hurr13ane** [comment]
#resolved
