### ISSUE TITLE
Two different project, 1 same link

### ISSUE THREAD

**Issue by axbecher** [hurr13ane/hurr13ane.com#8]
Link 5 and 6 ( see arrows ) send me to https://hurr13ane.com/Portfolio/logofolio/

But from 1 to 4 send me as well to that link.

![image](https://user-images.githubusercontent.com/72851811/161109492-7cfaa531-e8c3-4235-9577-90d2ca56a6bb.png)

Expected results:
1 and 2 should send me to: https://hurr13ane.com/Portfolio/employees-database/
3 and 4 should send me to: https://hurr13ane.com/Portfolio/happiness-statistics/

**Comment by hurr13ane** [comment]
#resolved
